name: Triage Issues to Project

on:
  issues:
    types:
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add New Issue to Project in "Not Looked At" section
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/ricky074game/projects/2
          github-token: ${{ secrets.TOKEN_GITHUB_PROJECT }}
          column-name: Not Looked At
